# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x07pb.auth\"F\n\x07UserReg\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\x04name\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\",\n\tUserLogin\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x08UserData\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"1\n\x05Token\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t2\xa0\x01\n\x0b\x41uthService\x12\x31\n\rCreateNewUser\x12\x10.pb.auth.UserReg\x1a\x0e.pb.auth.Token\x12/\n\tLoginUser\x12\x12.pb.auth.UserLogin\x1a\x0e.pb.auth.Token\x12-\n\x08\x41uthUser\x12\x0e.pb.auth.Token\x1a\x11.pb.auth.UserDataB\x11Z\x0fgo_auth/pb_authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017go_auth/pb_auth'
  _globals['_USERREG']._serialized_start=23
  _globals['_USERREG']._serialized_end=93
  _globals['_USERLOGIN']._serialized_start=95
  _globals['_USERLOGIN']._serialized_end=139
  _globals['_USERDATA']._serialized_start=141
  _globals['_USERDATA']._serialized_end=194
  _globals['_TOKEN']._serialized_start=196
  _globals['_TOKEN']._serialized_end=245
  _globals['_AUTHSERVICE']._serialized_start=248
  _globals['_AUTHSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
